### ISSUE TITLE
所有版本无法生成地形

### ISSUE THREAD

**Issue by Gold-Soul426** [SettingDust/TheAbyss#1]
我很喜欢你这个MOD的想法，但是实际上从0.1.0开始，到0.3.0,所有的版本都是无法生成地形（甚至0.1.0无法创建世界），只有少量的结构，然后我以为是信雅互联的问题，又尝试了使用1.20.1的fabric纯净包，依然无法实现地形的正常载入

**Comment by SettingDust** [comment]
大坑是 1000 半径，你 tp 一下看看？

**Comment by Gold-Soul426** [comment]
谢谢，最后我的解决办法是加上Lithostitched，最新版本的世界就能正常创建了，也许你应该把它加上前置要求

**Comment by SettingDust** [comment]
那有报错吗？

**Comment by SettingDust** [comment]
不过确实应该是必须的，目前在做新版本优化大坑边缘，但是会导致海洋出奇怪的问题，没找到原因 = =

![图片](https://github.com/user-attachments/assets/4e285d6f-ace9-417c-afaf-9a469a00c495)
![图片](https://github.com/user-attachments/assets/d92997b5-004c-4387-8cb6-503602602039)

**Comment by Gold-Soul426** [comment]
目前进入游戏不会报错，只找到了大坑，没有看到其他的结构，而且在有Tectonic的情况下，海洋群系显示会错误，会有类似平原的地形代替原本的群系，

**Comment by SettingDust** [comment]
> 目前进入游戏不会报错，只找到了大坑，没有看到其他的结构，而且在有Tectonic的情况下，海洋群系显示会错误，会有类似平原的地形代替原本的群系，

Tectonic 支持看来有些问题，可以暂时用没有添加这个支持的版本
用它是为了更高的山，不过看来不太行，之后找其他方法

**Comment by Gold-Soul426** [comment]
目前的版本还有一些结构例如古城会生成在大坑底部的虚空中，看上去会有些违和，要是最终效果不错的话会是个很不错的MOD，加油啊大佬

**Comment by SettingDust** [comment]
结构是需要修改结构文件的，不会集成在模组里，通过 Patched 来批量修改结构文件，添加放置的条件判断

**Comment by SettingDust** [comment]
有可能把兼容数据包集成在模组里，得想想
